[connections.snowflake]
account = "THXIUNB-PH46446"
user = "nikitamate012"
password = "vTpQ6ssshiRSEgX"
role = "ACCOUNTADMIN"
warehouse = "COMPUTE_WH"
database = "SNOWFLAKE_LEARNING_DB"
schema = "PUBLIC"